- id: detect-env-leakage
  name: Detect leaking environment variables
  description: This hook checks for leaking environment variables.
  entry: detect-env-leakage
  language: python
  types: [text]
